version: '3'

tasks:
  # Top-level test execution tasks
  test:admin:
    desc: Run admin-web E2E tests
    cmds:
      - python run_admin_tests.py --no-confirm

  test:public:
    desc: Run public-web E2E tests
    cmds:
      - python run_public_tests.py --no-confirm

  # Headless variants
  test:admin:headless:
    desc: Run admin-web tests in headless mode
    cmds:
      - TEST_HEADLESS=true python run_admin_tests.py --no-confirm

  test:public:headless:
    desc: Run public-web tests in headless mode
    cmds:
      - TEST_HEADLESS=true python run_public_tests.py --no-confirm

  # Interactive variants
  test:admin:interactive:
    desc: Run admin-web tests with confirmation prompt
    cmds:
      - python run_admin_tests.py

  test:public:interactive:
    desc: Run public-web tests with confirmation prompt
    cmds:
      - python run_public_tests.py

  # Individual admin-web tests
  test:admin:auth:
    desc: Run authentication flow test
    cmds:
      - python e2e/admin-web/auth-flow/test_auth_flow.py

  test:admin:dashboard:
    desc: Run dashboard navigation test
    cmds:
      - python e2e/admin-web/dashboard/test_dashboard_navigation.py

  test:admin:profile:
    desc: Run profile management tests
    cmds:
      - python e2e/admin-web/profile/test_profile.py

  test:admin:skills:
    desc: Run skills CRUD tests
    cmds:
      - python e2e/admin-web/skills/test_skills_crud.py

  test:admin:experience:
    desc: Run work experience CRUD tests
    cmds:
      - python e2e/admin-web/experience/test_experience_crud.py

  test:admin:certifications:
    desc: Run certifications CRUD tests
    cmds:
      - python e2e/admin-web/certifications/test_certifications_crud.py

  test:admin:projects:
    desc: Run portfolio projects CRUD tests
    cmds:
      - python e2e/admin-web/portfolio-projects/test_portfolio_projects_crud.py

  test:admin:paints:
    desc: Run miniatures paints CRUD tests
    cmds:
      - python e2e/admin-web/miniatures/test_paints_crud.py

  test:admin:themes:
    desc: Run miniatures themes CRUD tests
    cmds:
      - python e2e/admin-web/miniatures/test_themes_crud.py

  test:admin:miniatures:
    desc: Run miniatures projects CRUD tests
    cmds:
      - python e2e/admin-web/miniatures/test_projects_crud.py

  test:admin:messaging:
    desc: Run messaging CRUD tests
    cmds:
      - python e2e/admin-web/messaging/test_messaging_crud.py

  test:admin:rbac:
    desc: Run all RBAC tests (admin + demo user)
    cmds:
      - python e2e/admin-web/rbac/test_rbac_admin_walkthrough.py
      - python e2e/admin-web/rbac/test_rbac_demo_user.py

  test:admin:rbac:admin:
    desc: Run RBAC admin walkthrough test
    cmds:
      - python e2e/admin-web/rbac/test_rbac_admin_walkthrough.py

  test:admin:rbac:demo:
    desc: Run RBAC demo user restrictions test
    cmds:
      - python e2e/admin-web/rbac/test_rbac_demo_user.py

  # Individual public-web tests
  test:public:home:
    desc: Run home page test
    cmds:
      - python e2e/public-web/test_home_page.py

  test:public:contact:
    desc: Run contact form test
    cmds:
      - python e2e/public-web/test_contact_form.py

  test:public:gallery:
    desc: Run miniatures gallery test
    cmds:
      - python e2e/public-web/test_miniatures_gallery.py

  test:public:errors:
    desc: Run error pages test
    cmds:
      - python e2e/public-web/test_error_pages.py

  test:public:projects:
    desc: Run projects page test
    cmds:
      - python e2e/public-web/test_projects_page.py

  # Setup and configuration
  setup:
    desc: Set up testing environment
    cmds:
      - python -m pip install -r requirements.txt
      - python -m playwright install chromium
      - echo "Testing environment setup complete!"

  setup:dev:
    desc: Install development dependencies (linting tools)
    deps:
      - setup
    cmds:
      - echo "Development tools installed!"

  setup:env:
    desc: Create .env file from template
    cmds:
      - cmd: cp .env.example .env
        platforms: [linux, darwin]
      - cmd: copy .env.example .env
        platforms: [windows]
      - echo "Created .env file. Please edit it with your credentials."

  # Cleanup tasks
  clean:
    desc: Clean test artifacts and screenshots
    cmds:
      - cmd: rm -rf /tmp/*.png e2e/auth/.auth/
        platforms: [linux, darwin]
        ignore_error: true
      - cmd: if exist C:\tmp\*.png del C:\tmp\*.png
        platforms: [windows]
        ignore_error: true
      - cmd: if exist e2e\auth\.auth rmdir /s /q e2e\auth\.auth
        platforms: [windows]
        ignore_error: true
      - echo "Cleaned test artifacts"

  clean:cache:
    desc: Clean Python cache files
    cmds:
      - cmd: find . -type d -name __pycache__ -exec rm -rf {} +
        platforms: [linux, darwin]
        ignore_error: true
      - cmd: find . -type f -name "*.pyc" -delete
        platforms: [linux, darwin]
        ignore_error: true
      - cmd: for /d /r . %d in (__pycache__) do @if exist "%d" rmdir /s /q "%d"
        platforms: [windows]
        ignore_error: true
      - cmd: del /s /q *.pyc
        platforms: [windows]
        ignore_error: true
      - echo "Cleaned Python cache"

  # Documentation and help
  list:
    desc: List all available test suites
    cmds:
      - echo "Available test suites:"
      - echo ""
      - echo "  ADMIN-WEB TESTS:"
      - echo "    task test:admin              - Run all admin-web tests"
      - echo "    task test:admin:headless     - Run admin-web tests headless"
      - echo "    task test:admin:auth         - Authentication flow"
      - echo "    task test:admin:dashboard    - Dashboard navigation"
      - echo "    task test:admin:profile      - Profile management"
      - echo "    task test:admin:skills       - Skills CRUD"
      - echo "    task test:admin:experience   - Work experience CRUD"
      - echo "    task test:admin:certifications - Certifications CRUD"
      - echo "    task test:admin:projects     - Portfolio projects CRUD"
      - echo "    task test:admin:paints       - Miniatures paints CRUD"
      - echo "    task test:admin:themes       - Miniatures themes CRUD"
      - echo "    task test:admin:miniatures   - Miniatures projects CRUD"
      - echo "    task test:admin:messaging    - Messaging CRUD"
      - echo "    task test:admin:rbac         - All RBAC tests"
      - echo "    task test:admin:rbac:admin   - RBAC admin walkthrough"
      - echo "    task test:admin:rbac:demo    - RBAC demo user restrictions"
      - echo ""
      - echo "  PUBLIC-WEB TESTS:"
      - echo "    task test:public             - Run all public-web tests"
      - echo "    task test:public:headless    - Run public-web tests headless"
      - echo "    task test:public:home        - Home page"
      - echo "    task test:public:projects    - Projects page"
      - echo "    task test:public:contact     - Contact form"
      - echo "    task test:public:gallery     - Miniatures gallery"
      - echo "    task test:public:errors      - Error pages"

  check:env:
    desc: Check if .env file exists and is configured
    cmds:
      - cmd: |
          if [ ! -f .env ]; then
            echo "ERROR: .env file not found. Run 'task setup:env' to create it."
            exit 1
          fi
          if grep -q "your_username\|your_password" .env; then
            echo "WARNING: .env file contains default values. Please update with actual credentials."
          else
            echo "OK - .env file is configured"
          fi
        platforms: [linux, darwin]
      - cmd: 'python -c "import os,sys; sys.exit(0 if os.path.exists(''.env'') else (print(''ERROR: .env not found'') or 1))"'
        platforms: [windows]

  # Code quality tasks
  lint:
    desc: Run all linters (black, flake8, isort, pylint, mypy)
    cmds:
      - task: lint:black
      - task: lint:flake8
      - task: lint:isort
      - task: lint:pylint
      - task: lint:mypy

  lint:black:
    desc: Check code formatting with black
    cmds:
      - python -m black --check --diff .

  lint:flake8:
    desc: Lint code with flake8
    cmds:
      - python -m flake8 .

  lint:isort:
    desc: Check import sorting with isort
    cmds:
      - python -m isort --check-only --diff .

  lint:pylint:
    desc: Run pylint static analysis
    cmds:
      - python -m pylint e2e/ run_admin_tests.py run_public_tests.py

  lint:mypy:
    desc: Run mypy type checking
    cmds:
      - python -m mypy e2e/common e2e/auth run_admin_tests.py run_public_tests.py

  format:
    desc: Auto-format code with black and isort
    cmds:
      - python -m black .
      - python -m isort .
      - echo "Code formatted successfully!"

  format:check:
    desc: Check if code needs formatting (dry run)
    cmds:
      - python -m black --check .
      - python -m isort --check-only .

  # CI/CD tasks
  ci:all:
    desc: Run all CI checks (lint only, no tests)
    cmds:
      - task: lint:black
      - task: lint:flake8
      - task: lint:isort
      - task: lint:pylint
      - task: lint:mypy

  ci:admin:
    desc: Run CI checks for admin-web (lint + admin tests headless)
    cmds:
      - task: lint
      - task: check:env
      - TEST_HEADLESS=true python run_admin_tests.py --no-confirm

  ci:public:
    desc: Run CI checks for public-web (lint + public tests headless)
    cmds:
      - task: lint
      - task: check:env
      - TEST_HEADLESS=true python run_public_tests.py --no-confirm
